timeout: 30m0s

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - --tag=us.gcr.io/deepsource-dev/cppcheck-deepsource:dev
    - .

images: ['us.gcr.io/deepsource-dev/cppcheck-deepsource:dev']

options:
  machineType: 'E2_HIGHCPU_8'
